### ISSUE TITLE
Necessary Permissions

### ISSUE THREAD

**Issue by MScottBlake** [jssimporter/Spruce#12]
What permissions are necessary to make Spruce work?

**Comment by homebysix** [comment]
Can't guarantee this is 100% comprehensive, but here's what I'd guess by looking at the `retrieve_all()` references in the code:

| Object | Create | Read | Update | Delete |
| --- | --- | --- | --- | --- |
| Computers |  | X |  | X |
| Configurations |  | X |  |  |
| eBooks |  | X |  |  |
| File Share Distribution Points |  | X |  |  |
| iOS Configuration Profiles |  | X |  | X |
| Mobile Device Applications |  | X |  | X |
| Mobile Devices |  | X |  | X |
| OS X Configuration Profiles |  | X |  | X |
| Packages |  | X |  | X |
| Policies |  | X |  | X |
| Provisioning Profiles |  | X |  |  |
| Scripts |  | X |  | X |
| Smart Computer Groups |  | X |  | X |
| Smart Mobile Device Groups |  | X |  | X |
| Static Computer Groups |  | X |  | X |
| Static Mobile Device Groups |  | X |  | X |

**Comment by grahampugh** [comment]
I'll add this to the Wiki.

**Comment by grahampugh** [comment]
Table added to wiki.
