### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#13]
Seeing this post ElCap update on my iMac:

/Users/ega/Documents/Projects/Spruce-2.0.0/spruce.py -t > ./policies.txt
Traceback (most recent call last):
  File "/Users/ega/Documents/Projects/Spruce-2.0.0/spruce.py", line 1931, in <module>
    main()
  File "/Users/ega/Documents/Projects/Spruce-2.0.0/spruce.py", line 1927, in main
    run_reports(args)
  File "/Users/ega/Documents/Projects/Spruce-2.0.0/spruce.py", line 1757, in run_reports
    print_output(report, args.verbose)
  File "/Users/ega/Documents/Projects/Spruce-2.0.0/spruce.py", line 1379, in print_output
    print "\t%s" % line
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-8: ordinal not in range(128)

**Comment by agerstein** [comment]
Exact same error here. A full report won't output anything, and partial ones (computers, packages) don't seem to complete running (attached, along with computers run to STDIO and pasted into a file).

Machine is 10.10.3 and is the same workstation that I'm using for my AutoPkgr needs, which seems to be working ok at the moment.
[spruce-packages.txt](https://github.com/sheagcraig/Spruce/files/39352/spruce-packages.txt)
[spruce-computers.txt](https://github.com/sheagcraig/Spruce/files/39353/spruce-computers.txt)
[spruce-computers-handrun.txt](https://github.com/sheagcraig/Spruce/files/39355/spruce-computers-handrun.txt)

**Comment by nzmacgeek** [comment]
I would double check your list of computers, etc. It is likely that (especially in the modern world), one of your computers has a name that contains unicode characters and that Spruce hasn't accounted for that. 
The worst culprits for this are scripts that have been written in the JSS interface - if you haven't fixed your default text manipulation settings ("Smart Quotes"), then you'll get curly quotes in your scripts - which doesn't always throw up errors in Bash, etc - but when you're mucking around with XML and Python...

**Comment by sheagcraig** [comment]
I'm making some changes (pending testing) to python-jss for handling unicode better, and they should make there way down to spruce.

**Comment by agerstein** [comment]
Shea, has there been any progress on this issue?

**Comment by grahampugh** [comment]
Please all try with the latest release, which uses a much newer `python-jss`.
