### ISSUE TITLE
Feature request: List smart/static groups which aren't used in any scope

### ISSUE THREAD

**Issue by homebysix** [jssimporter/Spruce#2]
It would blow people's minds if Spruce could provide a report on the smart groups and static groups that are not currently being used in any scope. The pseudo-logic would look something like this:

```
$computer_groups = array_merge( $smart_computer_groups, $static_computer_groups )
$mobile_groups = array_merge( $smart_mobile_groups, $static_mobile_groups )

for each $group in $computer_groups {
    check for $group.id in all policy scopes
    check for $group.id in all configuration profile scopes
    check for $group.id in all managed preferences scopes
    check for $group.id in all restricted software scopes
    check for $group.id in all mac app store scopes
    check for $group.id in all ebooks scopes
    if any of the above is true { return } else { return $group }
}

for each $group in $mobile_groups {
    check for $group.id in all configuration profile scopes
    check for $group.id in all provisioning profile scopes
    check for $group.id in all mobile apps scopes
    check for $group.id in all ebooks scopes
    if any of the above is true { return } else { return $group }
}
```

I know many people have smart groups simply for reporting/monitoring purposes, but the above feature would really help us sort through which non-scoped groups are useful to us and which are not.

:thumbsup:

**Comment by sheagcraig** [comment]
Whoa-read my mind! I've been planning on adding this in. I think there's actually a TODO list somewhere in the project! But yes; I have so many groups created at different times that are no longer useful.

**Comment by homebysix** [comment]
I think you can consider this closed! Job well done. Raises all around.
