### ISSUE TITLE
mobile device group report listing group that is scoped to by an app

### ISSUE THREAD

**Issue by dnikles** [jssimporter/Spruce#21]
I ran spruce.py -r and generated a mobile device group report. I know at least one of the groups listed has an app scoped to that group. Not sure how I can show that here but happy to work with you on the issue.

**Comment by sheagcraig** [comment]
Gotcha.

So if you look about here: https://github.com/sheagcraig/Spruce/blob/master/spruce.py#L1129

You can see the logic this report uses to figure out what is unused. I would use the web interface or python-jss to pull the record for the group and the app you know are associated and see how they might be failing to get noticed by the above code.

**Comment by dnikles** [comment]
I think that area shows apps that are not scoped to users or groups but what I'm after are groups which are not scoped to by configs, apps, books, etc. Although maybe I'm just missing the logic. I know the App ID is 57 and the Group ID is 109. When I use GET /mobiledeviceapplications/id/57 I get 
```  
<scope>
    <all_mobile_devices>false</all_mobile_devices>
    <all_jss_users>false</all_jss_users>
    <mobile_devices/>
    <buildings/>
    <departments/>
    <mobile_device_groups>
      <mobile_device_group>
        <id>109</id>
```
returned, but group 109 is showing in the report for unused mobile device groups
