### ISSUE TITLE
No pkgs removed, am I stupid or is it not working with v10 cloud?

### ISSUE THREAD

**Issue by jby** [jssimporter/Spruce#25]
I've tried spruce to clean out old autopkg-pkgs that's now outdated, but it doesn't seem to do anything.

Am I doing something fundamentally wrong, or is it not working with a Jamf Pro v10 cloud?

Below is a log from my shell doing step-by-step, finishing with a diff of a run before and after --remove.

```bash
19:50:56 [jonasb:~/src/div/Spruce] master 1 ± ./spruce.py -p -o /tmp/pkgs
🌲  Building: Package Report... 🌲
🌲  Wrote output to /tmp/pkgs
19:51:13 [jonasb:~/src/div/Spruce] master ± ./spruce.py --remove /tmp/pkgs
Are you sure you want to continue deleting objects from https://[myjss].jamfcloud.com? (Y or N): Y
19:51:22 [jonasb:~/src/div/Spruce] master ± ./spruce.py -p -o /tmp/pkgs2
🌲  Building: Package Report... 🌲
🌲  Wrote output to /tmp/pkgs2
19:51:38 [jonasb:~/src/div/Spruce] master ± diff /tmp/pkgs /tmp/pkgs2
diff --git a/tmp/pkgs b/tmp/pkgs2
index d659715..d4dce15 100644
--- a/tmp/pkgs
+++ b/tmp/pkgs2
@@ -1,6 +1,6 @@
 <?xml version='1.0' encoding='UTF-8'?>
 <SpruceReport>
-    <ReportDate>20171213-195109</ReportDate>
+    <ReportDate>20171213-195134</ReportDate>
19:51:38 [jonasb:~/src/div/Spruce] master 1 ±
```

**Comment by grahampugh** [comment]
I'm going to guess that it takes more than 9 seconds to remove packages from all the clustered servers of Jamf Cloud instances.

**Comment by jby** [comment]
Well, yes, hence my question.
So, what am I doing wrong then - since Spruce is not doing anything?

**Comment by grahampugh** [comment]
Are you asking it to do anything? i.e. did you move anything into the `<Removals>` list?
