### ISSUE TITLE
Check for usage in Configurations as well...

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#3]
This is really an enhancement I think.  I got feedback from several of my Casper Site admins that they had 10s to 100s of packages that are used only in Casper Configurations and not policies.  Our folks would be interested in packages and scripts that are not used in anything (policy, configuration, whatever).

**Comment by sheagcraig** [comment]
Ah! Cool idea. I'll put that on the todo list for sure.

**Comment by amandaw33** [comment]
We have so many packages & scripts in configs, I'd love to have this functionality as well to really be able to utilize Spruce.

**Comment by kernsb** [comment]
I'll add a "me too" to this one. Ran into this right away.

**Comment by sheagcraig** [comment]
@everetteallen @amandaw33 @kernsb Check out Spruce 2.0. I don't use the Casper Imaging Configs, so I can't really test, but the code is all there and there's no reason it shouldn't work.

**Comment by kernsb** [comment]
Awesome! Was just starting to test with that now.

Thanks much for all of your work on this!

Brandon

**Comment by kernsb** [comment]
Just tested. This is indeed working properly! Scripts and Packages that I was previously having to manually remove from the report because they were being used in Casper Imaging are no longer appearing in the reports!

Brandon

**Comment by everetteallen** [comment]
Just to confirm this does work as desired.  I  used my test cloud instance to verify so working with jamfcloud.com hosted JSS instances.  Thanks!
