### ISSUE TITLE
UnboundLocalError when using a specified prefs file

### ISSUE THREAD

**Issue by danengh** [jssimporter/Spruce#50]
Running
`/usr/local/autopkg/python spruce.py --prefs edu.umn.oit.spruce.plist --scripts`

results in
`UnboundLocalError: local variable 'connection' referenced before assignment`

Here is the traceback
`Traceback (most recent call last):
  File "spruce.py", line 2249, in <module>
    main()
  File "spruce.py", line 2236, in main
    connect(args)
  File "spruce.py", line 2219, in connect
    JSSConnection.setup(connection)`

Additional error catching in the IF block on line 2389 will fix the traceback and can provide additional information about how to provide the file location.

Something like:
```        
        else:
            print("Unable to find file " + str(args.prefs))
            print("Add prefs file location like ~/Library/Preferences/com.company.preferences.plist")
            sys.exit()
```

**Comment by grahampugh** [comment]
I suspect you have a missing variable in your plist, as it works for me:

```bash
% /usr/local/autopkg/python spruce.py --prefs ~/sourcecode/config/jssimporter.plist --scripts
JSS: https://jss.server.com
Preferences used: /Users/gpugh/config/jssimporter.plist
*  Building: Scripts Report... *

*  Script Usage Report ********************** 

*  Unused (3)
   All scripts which are not installed by any policies or imaging
   configurations.

	FixtureScript.sh
	Register MAU.sh
	test.sh

*  Cruftiness *
*  Unscoped Script Cruftiness
	42.86%
```

I think there may be a mismatch in the variable names (e.g. `API_PASSWORD` vs `API_PASS`), will have to check. These are the variables used:

```python
    connection["url"] = prefs["JSS_URL"]
    connection["user"] = prefs["API_USERNAME"]
    connection["password"] = prefs["API_PASSWORD"]
    connection["ssl_verify"] = prefs.get("JSS_VERIFY_SSL", True)
    connection["suppress_warnings"] = prefs.get("JSS_SUPPRESS_WARNINGS", True)
    connection["jss_migrated"] = prefs.get("JSS_MIGRATED", True)
    connection["repo_prefs"] = prefs.get("JSS_REPOS")
```

There could be good reasons for wanting different credentials for JSSImporter and Spruce (since additional permissions are required to delete), but if that's the case, they could be better named.

**Comment by danengh** [comment]
I was missing the `.plist` from the file which was causing the error. All of the variables were there and labeled correctly but without the whole filename in there, it couldn't grab the creds to try them out.

The uncaught exception and traceback wasn't super helpful in helping me determine what the problem was initially. Added the `else` clause which narrowed down that the file path was the issue.

**Comment by grahampugh** [comment]
So this wasn't your actual command?

```/usr/local/autopkg/python spruce.py --prefs edu.umn.oit.spruce.plist --scripts```

**Comment by danengh** [comment]
It was. I had to expand it to `/usr/local/autopkg/python spruce.py --prefs ~/Library/Preferences/edu.umn.oit.spruce.plist --scripts` for it to run as expected.

**Comment by grahampugh** [comment]
Ah, makes sense. It's not the `defaults` command, so it does need to know the path to the plist.

I'll try and make the error more elegant/informative

**Comment by grahampugh** [comment]
Should be better in the latest push, tag 3.0.1
