### ISSUE TITLE
Add VirtualEnv to Spruce so that users only have to have python 3 installed.

### ISSUE THREAD

**Issue by pboushy** [jssimporter/Spruce#56]
VirtualEnv folders can be added to a project that contains all the modules needed.
If it is included in the project, then all users need to install is Python 3.

**Comment by grahampugh** [comment]
I'm not making updates to Spruce myself anymore but am open to a PR.

**Comment by pboushy** [comment]
I didn't see your note about recommending Prune instead of Spruce before I submitted this.

We can actually close this unless someone else wants it. Prune worked great for what I needed.
