### ISSUE TITLE
Confused about SSL

### ISSUE THREAD

**Issue by everetteallen** [jssimporter/Spruce#9]
So I want to do some spruce reporting from  individual JSS machines in a pool (i.e. hit their ip directly)
Made sure there was just python-jss defaults:
ls ~/Library/Preferences/com.github*
~/Library/Preferences/com.github.GitHub.LSSharedFileList.plist
~/Library/Preferences/com.github.sheagcraig.JSSRecipeCreator.plist
~/Library/Preferences/com.github.GitHub.plist
~/Library/Preferences/com.github.sheagcraig.python-jss.plist

Even overloaded the preferences file with different syntax  for SSL verify:

defaults read ~/Library/Preferences/com.github.sheagcraig.python-jss.plist
{
    "JSS_VERIFY_SSL" = 0;
    "jss_pass" = "uwish!";
    "jss_url" = "https://107.23.24.212:443/";
    "jss_user" = audit;
    "ssl_verify" = 0;
}

Then I get this below.  So am I confused ?  I get the name and the cert don't match but don't care.

~/Desktop/Spruce-testing/spruce.py --packages
🌲  Building: Package Report... 🌲
Traceback (most recent call last):
  File "~/Desktop/Spruce-testing/spruce.py", line 1668, in <module>
    main()
  File "~/Desktop/Spruce-testing/spruce.py", line 1664, in main
    run_reports(args)
  File "~/Desktop/Spruce-testing/spruce.py", line 1611, in run_reports
    results.append(func(*_args_dict))
  File "~/Desktop/Spruce-testing/spruce.py", line 781, in build_packages_report
    all_policies = jss_connection.Policy().retrieve_all(
  File "/Library/Python/2.7/site-packages/jss/jss.py", line 440, in Policy
    return self.factory.get_object(Policy, data, subset)
  File "/Library/Python/2.7/site-packages/jss/jss.py", line 525, in get_object
    result = self.jss.get(url)
  File "/Library/Python/2.7/site-packages/jss/jss.py", line 232, in get
    response = self.session.get(request_url)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname '107.23.24.212' doesn't match either of '*.jamfcloud.com', 'jamfcloud.com'

**Comment by sheagcraig** [comment]
spruce will use the AutoPkg preferences first, if they are present, and then use python-jss. So first off, make sure it's not using the AutoPkg prefs.

But it looks like maybe this is a SNI issue?

What version of python-jss is it using? I've started including the dependencies that are (allegedly) needed for SNI support as part of the setup, but you would need a fairly current one to have them.

**Comment by everetteallen** [comment]
Confirmed I am not using autopkg prefs.
`defaults read com.github.autopkg
2015-08-26 14:35:32.494 defaults[37660:8740977] 
Domain com.github.autopkg does not exist
`
Looks like 1.3.0
pip list |grep jss
python-jss (1.3.0)

**Comment by sheagcraig** [comment]
Dang. That's as new as it gets.

Do you have ndg-httpsclient and pyasn1 installed as well (python packages)?

**Comment by everetteallen** [comment]
pip list |grep http
ndg-httpsclient (0.4.0)
pip list |grep pyasn
pyasn1 (0.1.8)

**Comment by sheagcraig** [comment]
I mean, it is true that `'107.23.24.212' doesn't match either of '*.jamfcloud.com', 'jamfcloud.com'.` I would think that it would do a dns lookup of that IP before saying that, but maybe it doesn't? And there's no way to specify the individual host because that just gives you the collective?

**Comment by everetteallen** [comment]
Either way will never match a service cert...

**Comment by everetteallen** [comment]
host nc.jamfcloud.com
nc.jamfcloud.com is an alias for...

**Comment by sheagcraig** [comment]
I get that too when I hit ours (which has a wildcard cert) with the IP address instead of the hostname. I think if the API is only HTTPS and there's a wildcard cert, it's going to have to be a hostname that matches that cert.

**Comment by everetteallen** [comment]
So the question is how far should ssl_verify false go?  Browsers warn but kick thru essentially ignoring all certificate issues.  JAMF has the idea of not requiring the certificate to be verified at all in GUI tools.
Are we comfortable with the same in Spruce?

**Comment by sheagcraig** [comment]
Well, the ssl_verify is entirely just to verify that the traffic from the JSS is encrypted with a cert that you trust. It is not the cert used to decode the SSL stream from the JSS.

I have it on by default, but honestly it's not really helping anything.
